exo player dynamic
invideoio/korvi pull request #4
Opened 2021-11-20 09:39 UTC by dhruv2295

Expose exoplayer to main project to update media in same instance

2021-11-20 09:40 UTC, sahilbajaj commented on gradle.properties
> +version=2.2.4
2.2.1-IV2

2021-11-20 09:48 UTC, sahilbajaj requested changes
changes

2021-11-20 10:02 UTC, dhruv2295 commented on gradle.properties
> +version=2.2.4
done

2021-11-24 06:33 UTC, sahilbajaj approved these changes

2021-11-24 06:33 UTC, merged